language: c

os: linux

addons:
  apt:
    packages:
      - libc6-dev-i386
      - dpkg

cache:
  pip: true
  directories:
    - devenv

env:
  global:
    - BOLOS_ENV=$TRAVIS_BUILD_DIR/devenv
    - BOLOS_SDK=$TRAVIS_BUILD_DIR/devenv/nanos-secure-sdk-f9e1c7b8904df2eee0ae7e603f552b876c169334

install:
  - sudo apt-get install libusb-1.0-0-dev libudev-dev
  - pip install --user ledgerblue
  - mkdir -p devenv && cd devenv && ../scripts/prepare-devenv.sh && cd ..
  - wget http://mirrors.kernel.org/ubuntu/pool/main/g/gcc-8/libstdc++6_8-20180414-1ubuntu2_amd64.deb
  - sudo dpkg --force-all -i libstdc++6_8-20180414-1ubuntu2_amd64.deb
  - wget http://mirrors.kernel.org/ubuntu/pool/main/n/ncurses/libtinfo5_6.1-1ubuntu1_amd64.deb
  - sudo dpkg -i libtinfo5_6.1-1ubuntu1_amd64.deb

script:
  - make release

before_deploy:
  - export RELEASE_IDENTIFIER=$(make load-offline | grep "Application full hash")
  - export RELEASE_FILENAME=$(ls aeternity-ledger-app-*.tar.gz)

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: $RELEASE_FILENAME
    body: $RELEASE_IDENTIFIER
    skip_cleanup: true
    on:
      tags: true
