language: c

os: linux

addons:
  apt:
    packages:
      - libc6-dev-i386
      - dpkg

cache:
  pip: true
  directories:
    - devenv

env:
  global:
    - BOLOS_ENV=$TRAVIS_BUILD_DIR/devenv
    - BOLOS_SDK=$TRAVIS_BUILD_DIR/devenv/nanos-secure-sdk-nanos-1421

install:
  - mkdir -p devenv && cd devenv && ../scripts/prepare-devenv.sh && cd ..
  - wget http://mirrors.kernel.org/ubuntu/pool/main/g/gcc-8/libstdc++6_8-20180414-1ubuntu2_amd64.deb
  - sudo dpkg --force-all -i libstdc++6_8-20180414-1ubuntu2_amd64.deb
  - wget http://mirrors.kernel.org/ubuntu/pool/main/n/ncurses/libtinfo5_6.1-1ubuntu1_amd64.deb
  - sudo dpkg -i libtinfo5_6.1-1ubuntu1_amd64.deb
  - pip install --user Pillow

script:
  - make

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: bin/app.hex
    skip_cleanup: true
    on:
      tags: true
